### ISSUE TITLE
Look into using Hall Effect keycaps for velocity and aftertouch

### ISSUE THREAD

**Issue by hammerandtongs** [stonepreston/LMN-3-Firmware#2]
https://github.com/WootingKb/wooting-analog-midi

This is a hall effect keycap custom designed for gaming by wooting. They have a special key that they have made that gives the full analog value to the keystroke from their lekker keyswitch.

https://wooting.io/lekker

**Comment by stonepreston** [comment]
awesome! will keep this in mind for future releases
